# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pathlib

from PyQt5 import QtCore, QtGui, QtWidgets
from defines import ROOT_DIR

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 340)
        MainWindow.setStyleSheet("background-color: #2196f3;")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.originalTextField = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.originalTextField.setEnabled(True)
        self.originalTextField.setStyleSheet("background-color: #fafafa;\n"
"font-size: 20px;")
        self.originalTextField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.originalTextField.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.originalTextField.setObjectName("originalTextField")
        self.verticalLayout.addWidget(self.originalTextField)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.swapLabelButton = QtWidgets.QLabel(self.centralwidget)
        self.swapLabelButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.swapLabelButton.setFont(font)
        self.swapLabelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.swapLabelButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.swapLabelButton.setText("")
        self.swapLabelButton.setPixmap(QtGui.QPixmap(str(ROOT_DIR / "icons" / "swap_vert_black_24dp.svg")))
        self.swapLabelButton.setScaledContents(False)
        self.swapLabelButton.setAlignment(QtCore.Qt.AlignCenter)
        self.swapLabelButton.setIndent(-1)
        self.swapLabelButton.setObjectName("swapLabelButton")
        self.horizontalLayout.addWidget(self.swapLabelButton)
        self.favouriteLabelButton = QtWidgets.QLabel(self.centralwidget)
        self.favouriteLabelButton.setBaseSize(QtCore.QSize(0, 0))
        self.favouriteLabelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.favouriteLabelButton.setStyleSheet("padding-left: 5px;")
        self.favouriteLabelButton.setText("")
        self.favouriteLabelButton.setPixmap(QtGui.QPixmap(str(ROOT_DIR / "icons" / "star_rate_black_24dp.svg")))
        self.favouriteLabelButton.setObjectName("favouriteLabelButton")
        self.horizontalLayout.addWidget(self.favouriteLabelButton)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.translatedTextField = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.translatedTextField.setEnabled(True)
        self.translatedTextField.setMinimumSize(QtCore.QSize(0, 0))
        self.translatedTextField.setStyleSheet("background-color: #fafafa;\n"
"font-size: 20px;")
        self.translatedTextField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.translatedTextField.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.translatedTextField.setReadOnly(False)
        self.translatedTextField.setObjectName("translatedTextField")
        self.verticalLayout.addWidget(self.translatedTextField)
        self.notesField = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.notesField.setStyleSheet("background-color: #fafafa;\n"
"font-size: 20px;")
        self.notesField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notesField.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notesField.setObjectName("notesField")
        self.verticalLayout.addWidget(self.notesField)
        self.gridLayout.addLayout(self.verticalLayout, 0, 6, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listenSrcTextLabelButton = QtWidgets.QLabel(self.centralwidget)
        self.listenSrcTextLabelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listenSrcTextLabelButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listenSrcTextLabelButton.setAutoFillBackground(False)
        self.listenSrcTextLabelButton.setStyleSheet(";")
        self.listenSrcTextLabelButton.setText("")
        self.listenSrcTextLabelButton.setPixmap(QtGui.QPixmap(str(ROOT_DIR / "icons" / "volume_up_black_24dp.svg")))
        self.listenSrcTextLabelButton.setObjectName("listenSrcTextLabelButton")
        self.verticalLayout_2.addWidget(self.listenSrcTextLabelButton)
        self.originalLangComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.originalLangComboBox.setObjectName("originalLangComboBox")
        self.verticalLayout_2.addWidget(self.originalLangComboBox)
        self.listenDstTextLabelButton = QtWidgets.QLabel(self.centralwidget)
        self.listenDstTextLabelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listenDstTextLabelButton.setText("")
        self.listenDstTextLabelButton.setPixmap(QtGui.QPixmap(str(ROOT_DIR / "icons" / "volume_up_black_24dp.svg")))
        self.listenDstTextLabelButton.setObjectName("listenDstTextLabelButton")
        self.verticalLayout_2.addWidget(self.listenDstTextLabelButton)
        self.translatedLangComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.translatedLangComboBox.setObjectName("translatedLangComboBox")
        self.verticalLayout_2.addWidget(self.translatedLangComboBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.originalTextField.setPlaceholderText(_translate("MainWindow", "Original text"))
        self.translatedTextField.setPlaceholderText(_translate("MainWindow", "Translated text"))
        self.notesField.setPlaceholderText(_translate("MainWindow", "Notes"))
